"""Public configuration template for Test 3 (Binary Telemetry Bench).

Copy this file to `test3_config.py` on your PC and transfer to the M5Stack.
Never commit `test3_config.py` to git.
"""

# Safety interlock: set to True only after confirming target is an isolated bench backend
TEST3_ISOLATED_BENCH = False

# Local Wi-Fi network credentials
WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

# Target backend API base URL (LAN IP of your computer running FastAPI, NOT localhost)
# Example: "http://192.168.1.45:8000"
API_BASE_URL = "http://192.168.1.XX:8000"

# Provisioned test device credentials (generated by backend/scripts/test3_binary_bench.py prepare)
TRANSPORT_ID = 101
DEVICE_SECRET = "0000000000000000000000000000000000000000000000000000000000000000"

# Bench parameters
HTTP_TIMEOUT_SECONDS = 10
BENCH_SYNTHETIC_TIMESTAMP = 1726588800  # Unix UTC timestamp used for synthetic cases
