"""add_gin_index_alert_metadata

Revision ID: 093cf2d65539
Revises: 0a6e1e7a1828
Create Date: 2026-08-19 22:43:21.666036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '093cf2d65539'
down_revision: Union[str, None] = '0a6e1e7a1828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_animal_type', 'alerts', ['animal_id', 'type'], unique=False)
    op.create_index('ix_alerts_metadata_gin', 'alerts', ['alert_metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_metadata_gin', table_name='alerts', postgresql_using='gin')
    op.drop_index('ix_alerts_animal_type', table_name='alerts')
    # ### end Alembic commands ###
