"""add_daily_behavior_summary_table

Revision ID: 187d38a14511
Revises: 2082c4e4b0dc
Create Date: 2026-08-19 14:59:44.429020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '187d38a14511'
down_revision: Union[str, None] = '2082c4e4b0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_behavior_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pct_active', sa.Float(), nullable=False),
    sa.Column('pct_resting', sa.Float(), nullable=False),
    sa.Column('n_predictions', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'date', name='uq_animal_date')
    )
    op.create_index(op.f('ix_daily_behavior_summary_animal_id'), 'daily_behavior_summary', ['animal_id'], unique=False)
    op.create_index(op.f('ix_daily_behavior_summary_date'), 'daily_behavior_summary', ['date'], unique=False)
    op.create_index(op.f('ix_daily_behavior_summary_id'), 'daily_behavior_summary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_behavior_summary_id'), table_name='daily_behavior_summary')
    op.drop_index(op.f('ix_daily_behavior_summary_date'), table_name='daily_behavior_summary')
    op.drop_index(op.f('ix_daily_behavior_summary_animal_id'), table_name='daily_behavior_summary')
    op.drop_table('daily_behavior_summary')
    # ### end Alembic commands ###
